import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'modern-normalize';
import "./globals.css";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;
  sidebar?: ReactNode;
  modal?: ReactNode;
}

export default function RootLayout({
  children, sidebar, modal,
}: Readonly<LayoutProps>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TanStackProvider>
          <Header />
          <main>
            <div className="flex">
              <aside className="w-64">
                {sidebar}
              </aside>
              <div className="flex-1">
                {children}
                {modal}
              </div>
            </div>
          </main>
          <Footer />
        </TanStackProvider>
      </body>
    </html>
  );
}
